apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-todolist
  template:
    metadata:
      labels:
        app: my-todolist
    spec:
      containers:
      - name: todolist
        image: christian-paul-ruales/todolist
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
